export const APP_CONSTANT = {
  LOCALE_DATE_STRING: 'en-US' , // Date Format
  FRIEND_REQUESTS_LIMIT: 20,
  POST_LIMIT: 3,
  MEMBERS_LIMIT: 6,
  GROUPS_LIMIT: 9,
  OTHER_GROUPS_LIMIT: 5,
  OTHER_GROUPS_TOP_LIST_LIMIT: 5,
  CHAT_MESSAGE_LIMIT: 50,
};
