export const Images = {
  likeIcon: require("../assets/images/Like.svg"),
  logo: require("../assets/images/logo.svg"),
  arrowRightIcon: require("../assets/images/arrowRight.svg"),
  checkIcon: require("../assets/images/check .svg"),
  crossIcon: require("../assets/images/x.svg"),
  medalStarIcon: require("../assets/images/medalStar.svg"),
  newIcon: require("../assets/images/new.svg"),
  newBlackIcon: require("../assets/images/newBlack.svg"),
  starIcon: require("../assets/images/star.svg"),
  friendsIcon: require("../assets/images/profile-2user.svg"),
  musicIon: require("../assets/images/music.svg"),
  startIcon: require("../assets/images/start.svg"),
  inActiveLikeIcon: require("../assets/images/inactiveLike.svg"),
  undoIcon: require("../assets/images/undo.svg"),
  moreOptionsIcon: require("../assets/images/moreOptions.svg"),
  shoppingCartIcon: require("../assets/images/shoppingCart.svg"),
  friendsProfileIcon: require("../assets/images/friendsProfile-2users.svg"),
  profileTickIcon: require("../assets/images/profileTick.svg"),
  locationIcon: require("../assets/images/locationIcon.svg"),
  gpsIcon: require("../assets/images/gps.svg"),
  profileAdIcon: require("../assets/images/profilead.svg"),
  uploadImageIcon: require("../assets/images/uploadProductImage.svg"),
  brandLogo: require("../assets/images/brandLogo.svg"),
  homeBackgroundImage: require("../assets/images/home-bg.png"),
  authBrandLogo: require("../assets/images/authBrandLogo.svg"),
  personalAccount: require("../assets/images/personal-account.png"),
  businessAccount: require("../assets/images/business-account.png"),
  spinner: require("../assets/images/spinner.svg"),
  eyeIcon: require("../assets/images/eye.png"),
  phoneCallIcon: require("../assets/images/phoneCall.svg"),
  crossIcon: require("../assets/images/cross.svg"),
  leftBackIcon: require("../assets/images/leftBack.svg"),
  activePaymentIcon: require("../assets/images/activePayment.svg"),
  paymentIcon: require("../assets/images/payment.svg"),

  activePurchaseIcon: require("../assets/images/activePurchase.svg"),
  purchaseIcon: require("../assets/images/purchase.svg"),

  activeSecurityIcon: require("../assets/images/activeSecurity.svg"),
  securityIcon: require("../assets/images/security.svg"),

  activeNotificationIcon: require("../assets/images/activeNotification.svg"),
  notificationIcon: require("../assets/images/notification.svg"),

  activeContactIcon: require("../assets/images/activeContact.svg"),
  contactIcon: require("../assets/images/contact.svg"),

  activeLegalIcon: require("../assets/images/activeLegal.svg"),
  legalIcon: require("../assets/images/legal.svg"),

  activeAdsManagementIcon: require("../assets/images/activeAdsManagement.svg"),
  adsManagementIcon: require("../assets/images/adsManagement.svg"),

  chevronRightIcon: require("../assets/images/chevron-right.svg"),
  activeChevronRightIcon: require("../assets/images/active-chevron-right.svg"),

  successIcon: require("../assets/images/success.svg"),
  emailUsIcon: require("../assets/images/emailUs.svg"),
  callUsIcon: require("../assets/images/callUs.svg"),
  addPaymentIcon: require("../assets/images/addPayment.svg"),
  callIcon: require(`../assets/images/call.svg`),
  videoIcon: require(`../assets/images/video.svg`),
  minimizeIcon: require(`../assets/images/DownArrow.svg`),
  maximizeArrow: require(`../assets/images/maximizeArrow.svg`),
  expandIcon: require(`../assets/images/Expand.svg`),
  playIcon: require("../assets/images/Play.svg"),
  sendIcon: require("../assets/images/Send.svg"),
  voiceIcon: require("../assets/images/Voice.svg"),
  fastestGrowingIcon: require("../assets/images/fastestGrowing.svg"),
  starBadeIcon: require("../assets/images/starBadge.svg"),

  //Header Icons
  coin: require("../assets/images/coin.svg"),
  selectedCoin: require("../assets/images/selectedCoin.svg"),
  global: require("../assets/images/global.svg"),
  selectedGlobal: require("../assets/images/selectedGlobal.svg"),
  home: require("../assets/images/home.svg"),
  selectedHome: require("../assets/images/selectedHome.svg"),
  message: require("../assets/images/message.svg"),
  selectedProfile: require("../assets/images/selectedProfile.svg"),
  profile: require("../assets/images/profile.svg"),
  blueCheckIcon: require("../assets/images/checkBlue.svg"),
  notifyLike: require("../assets/images/notifyLike.svg"),
  notifyMessage: require("../assets/images/notifyMessage.svg"),
  notifyProfile: require("../assets/images/notifyProfile.svg"),
  camera: require("../assets/images/camera.png"),
  blueCamera: require("../assets/images/camera-blue.png"),
  verifyEmail: require("../assets/images/email-sent.png"),
  redWarningIcon: require("../assets/images/redWarning.svg"),
  copyIcon: require("../assets/images/copy.svg"),
  globe: require("../assets/images/globe.svg"),
  photography: require("../assets/images/photography.svg"),
  realState: require("../assets/images/realState.svg"),
  tech: require("../assets/images/tech.svg"),
  groupMusic: require("../assets/images/groupMusic.svg"),
  crypto: require("../assets/images/crypto.svg"),
  doubleArrowRightBlueIcon: require("../assets/images/doubleArrowRightBlue.svg"),
  xRedIcon: require("../assets/images/xRed.svg"),
  greyBadgeIcon: require("../assets/images/greyBadgeIcon.svg"),
  callOutGoing: require("../assets/images/callOutGoing.svg"),
  userProfile: require("../assets/images/userProfile.svg"),
  settings: require("../assets/images/settings.svg"),
  shareIcon: require("../assets/images/shareWhite.svg"),
  leaveIcon: require("../assets/images/leave.svg"),
  searchMagnifyIcon: require("../assets/images/searchMagnify.svg"),
  starYellowIcon: require("../assets/images/staryellow.svg"),
  dustbinIcon: require("../assets/images/dustbin.svg"),
  masterCardIcon: require("../assets/images/masterCard.svg"),
  searchIcon: require("../assets/images/serach.svg"),
  profileCover: require("../assets/images/profilecover.svg"),
};
