export const types = {
  // Common
  SET_FORM_LODER: "SET_FORM_LODER",
  SET_FORM_ERRORS: "SET_FORM_ERRORS",
  SET_MESSAGE: "SET_MESSAGE",

  // Auth
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_FAILED: "OTP_FAILED",
  PROFILE_COMPLETED: "PROFILE_COMPLETED",
  RECOVER_PASSWORD: "RECOVER_PASSWORD",

  // USER
  UPDATE_PROFILE: "UPDATE_PROFILE",

  // Notification
  ADD_NOTIFICATIONS: 'ADD_NOTIFICATIONS',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',

  // Chat
  SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',
  CLOSE_ACTIVE_CHAT: 'CLOSE_ACTIVE_CHAT',
  ADD_MESSAGE_TO_CHAT: 'ADD_MESSAGE_TO_CHAT',
  NEW_CHAT: 'NEW_CHAT',
};
